//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chart_Leader.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public string CardType { get; set; }
        public int CardNumber { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string NameOfCard { get; set; }
        public string username { get; set; }
    
        public virtual membre membre { get; set; }
    }
}
