//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chart_Leader.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class membre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public membre()
        {
            this.Card = new HashSet<Card>();
            this.changePassword = new HashSet<changePassword>();
        }
    
        public string username { get; set; }
        public string password_ { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string compagny { get; set; }
        public string gender { get; set; }
        public System.DateTime birthdate { get; set; }
        public string question { get; set; }
        public string answer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Card> Card { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<changePassword> changePassword { get; set; }
    }
}
