//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chart_Leader.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shopping_Card
    {
        public int TempOrderID { get; set; }
        public int P_ID { get; set; }
        public string P_Name { get; set; }
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
    }
}
